### ISSUE TITLE
Support 2D datasets

### ISSUE THREAD

**Issue by lindholc** [lasp/hapi-server#52]
The LaTiS 2 interpreter assumes simple time series. We're not yet making use of HAPI's capabilities for additional dimensions. The spec states that datasets with more than two dimensions are experimental, so perhaps we can just support up to two for now.

**Comment by dlindhol** [comment]
I'd add that since `time` is expected to be the first dimension, that leaves one more. For LISIRD, that is the spectral dimension. I wouldn't want anyone thinking that we are talking about 2D *gridded* datasets here.

**Comment by lindholc** [comment]
What's a better way of saying what we mean?

**Comment by dlindhol** [comment]
I think this is fine since HAPI specifies that the first dimension is time. I just figured the clarification wouldn't hurt since my mind immediately goes to "grids" when I hear "2D".
